# Package files
name: Pack release

on:
  workflow_dispatch:
    inputs:
        version:
          description: 'New Version'
          required: true
          default: '-no-version'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: checkout 
      uses: actions/checkout@v3

    - name: package
      run: |
        mkdir ShotgunTurret
        cp -r About Defs Textures README.md version.txt ShotgunTurret
        zip -r ShotgunTurret-v${{ github.event.inputs.version }}.zip ./ShotgunTurret

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "ShotgunTurret-v${{ github.event.inputs.version }}.zip"
        name: "Release v${{ github.event.inputs.version }}"
        tag: "v${{ github.event.inputs.version }}"
        commit: "master"
        
        
