# Package files
name: Pack release

on:
  workflow_dispatch:
    inputs:
        version:
          description: 'New Version'
          required: true
          default: 'no-version'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: checkout 
      uses: actions/checkout@v3
      
    - name: package
      run: |
        zip -r ShotgunTurret.zip ./*
        
    - name: Upload Package
      id: upload-package
      uses: actions/upload-release-asset@v1
      with:
        asset_path: ShotgunTurret.zip
        asset_name: ShotgunTurret-${{ github.event.inputs.version }}.zip
      
