# Package files
name: Pack release

on:
  workflow_dispatch:
    inputs:
        version:
          description: 'New Version'
          required: true
          default: 'no-version'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: package
      run: |
        mkdir ShotgunTurret
        cp -r About/ Defs/ Textures/ Readme.md ShotgunTurret
        zip -9 -r ShotgunTurret.zip ShotgunTurret
    - name: Upload Package
      id: upload-package
      uses: actions/upload-release-asset@v1
  
      with:
        asset_path: ShotgunTurret.zip
        asset_name: ShotgunTurret-${{ github.event.inputs.version }}.zip
      
