# Package files
name: Pack release

on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Remove unnecessary files
      run: rm -rf Svgs
    - name: Pack release
      run: zip -r release.zip ./*
    - uses: actions/upload-artifact@v2
      with:
        name: release.zip
        path: release.zip
